#!/usr/bin/env bash

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

libraries=( $(${dir}/list-packages) )

git_reset() {
    echo "Resetting changes"
    git reset >/dev/null
}

trap git_reset ERR

git_reset

git add -A terrafomo-gen/config/*.yaml
git commit -m "Updating provider generator configuration"

git add -A terrafomo-gen/model/*.json terrafomo-gen/ir/*.json
git commit -m "Updating provider models and intermediate representation"

git add -A provider/terrafomo-*
git commit -m "Regenerating provider packages"

echo "Done."
