#!/usr/bin/env bash

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docs=( documentation )
core=( terrafomo )
libraries=( $(${dir}/list-packages) )

entry() {
    local ver="$1"
    local lib="$2"

cat <<-ENTRY
    - env: GHCVER=${ver} LIBRARY=${lib}
      addons: { apt: { packages: [ghc-${ver}], sources: [hvr-ghc] } }
ENTRY
}

matrix() {
    local title="$1"
    declare -a versions=("${!2}")
    declare -a selected=("${!3}")

cat <<-TITLE

    # ${title}
TITLE

    for lib in ${selected[@]}; do
        for ver in ${versions[@]}; do
            entry $ver $lib
        done
    done
}

ghc_820=( 8.2 )

travis=".travis.yml"

echo "Updating ${travis}"

sed -i -e '/# GENERATED/,/# END GENERATED/d' "${travis}"

echo "# GENERATED"                             >> "${travis}"
matrix "Core" ghc_820[@] core[@]               >> "${travis}"
if [ ${#libraries[@]} -ne 0 ]; then
    matrix "Libraries" ghc_820[@] libraries[@] >> "${travis}"
fi
echo "# END GENERATED"                         >> "${travis}"

echo "Done."
