#!/usr/bin/env bash

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

packages=( $(${dir}/list-packages) )

for config in stack-*.yaml; do
    echo "Updating ${config}"

    sed -i -e '/# GENERATED/,/# END GENERATED/d' "${config}"

    echo "# GENERATED" >> "${config}"

    if [ ${#packages[@]} -ne 0 ]; then
       echo "$(printf '  - %s\n' "${packages[@]}")" >> "${config}"
    fi

    echo "# END GENERATED" >> "${config}"
done

echo "Done."
