#!/usr/bin/env bash

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

config=".gitlab-ci.yml"
libraries=( $(${dir}/list-packages) )

output=""

if [ ${#libraries[@]} -ne 0 ]; then
    output=$output$(printf '    - %s/.stack-work\\n' "${libraries[@]}")
fi

if [ "${output}" != "" ]; then
    echo "Updating ${config}"

    replace="# GENERATED\\n$output# END GENERATED\\n"

    sed -i -n "/# GENERATED/{:a;N;/# END GENERATED/!ba;N;s:.*\\n:$replace:};p" "${config}"

    echo "Done."
fi
