#!/usr/bin/env bash

set -euo pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

config=".travis.yml"

core=( terrafomo terrafomo-gen terrafomo-example )
packages=( $(${dir}/list-packages) )

entry() {
    local ver="$1"
    local pkg="$2"

cat <<-ENTRY
    - env: CABALVER=2.2 GHCVER=${ver} PACKAGE=${pkg}
      compiler: ": #GHC ${ver}"
      addons: {apt: {packages: [cabal-install-2.2,ghc-8.4.3,alex-3.1.7,happy-1.19.5], sources: [hvr-ghc]}}

ENTRY
}

matrix() {
    declare -a versions=("${!1}")
    declare -a selected=("${!2}")

    for lib in ${selected[@]}; do
        for ver in ${versions[@]}; do
            entry $ver $lib
        done
    done
}

ghc_843=( 8.4.3 )

if [ ${#packages[@]} -ne 0 ]; then
    echo "Updating ${config}"

    sed -i -e '/# GENERATED/,/# END GENERATED/d' "${config}"

    echo "# GENERATED"            >> "${config}"
    matrix ghc_843[@] core[@]     >> "${config}"
    matrix ghc_843[@] packages[@] >> "${config}"
    echo "# END GENERATED"        >> "${config}"
fi

echo "Done."
